---
spring:
  profiles: local
  data:
    mongodb:
      host: localhost
      port: 27017
      database: petstore

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

app:
  env: "Local"
